pipelines:
  branches:
    devops:
    - step:
          name: Connect to EC2 instance 
          image: ubuntu:latest
          script:
             - cat <<< "$PEM_LIGHT_KEY" | base64 --decode > tek-staging.pem
             - chmod 400 tek-staging.pem
             - apt-get update
             - apt-get -y install openssh-client
             - ssh -v -o StrictHostKeyChecking=no -i tek-staging.pem ubuntu@$MACHINE_LIGHT_IP "cd /home/ubuntu/spacemartets && git fetch origin && git reset --hard origin/staging && cd admin/ && sudo docker compose -f docker-stg.yml down && sudo docker compose -f docker-stg.yml up -d --build"