version: '3'

services:
  php:
    build: .
    image: ${PROJECT_SLUG}_php
    env_file:
      - ./.env
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - redis

  redis:
    image: redis:latest

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_SLUG}_nginx
    ports:
      - "9009:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html
    depends_on:
      - php

networks:
  spacemarkets-backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.24.9/24